local scene = Scene.Create("probe", "", OcTree.Create())
Scene.SetActive(scene)
local node = SceneNode.Create("Ocean")
scene:GetRootNode():AddChild(node)
local ocean = OceanComponent.Create()
ocean:SetWaveAssetPath("Engine/Ocean/ocean.json") -- engine baseline bake
node:AddComponent(ocean)
print("resolved:", ocean:GetResolvedSource(), ocean:GetResolvedReason())
print("vertex count (infinite):", ocean:GetOceanVertexCount())
ocean:UpdateCameraFollow(Vector4(12345.0, 0.0, -6789.0, 1.0))
ocean:SetWaveTime(1.3)
print("wave height at origin:", ocean:WaveHeightAtWorld(0.0, 0.0))
print("wave height elsewhere:", ocean:WaveHeightAtWorld(1234.5, -987.6))
ocean:SetMode(0)
print("vertex count (finite 128):", ocean:GetOceanVertexCount())
